spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
   url: jdbc:h2:file:C:/data/product
   driverClassName: org.h2.Driver
   username: sa
   password: password
   
# Mysql DB Configration
# datasource:
#    url: jdbc:mysql://localhost:3306/***Your Schema***
#    username: ******
#    password: ********
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

server:
  port: 9050
      